# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

remote_theme: irubataru/alpha-jekyll-theme

# Site settings
title: Alpha
subtitle: "by HTML5 UP"
email: email@address.com
description: The Jekyll version of the Alpha theme by HTML5 UP.
baseurl: "/alpha-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://irubataru.github.io" # the base hostname & protocol for your site

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
github: mygithub
twitter: mytwittername
facebook: myfacebook
instagram:
dribbble: 
google_plus:

# Build settings
markdown: kramdown

include:
  - _pages

compress_html:
  clippings: []
  blanklines: false
  comments: all
